#!/command/with-contenv sh
set -a
source /etc/webtor/common.env
source /etc/webtor/secrets/api.env
WEBTOR_API_KEY=$API_KEY
WEBTOR_API_SECRET=$API_SECRET
TORRENT_HTTP_PROXY_SERVICE_PORT=$WEB_PORT
TORRENT_HTTP_PROXY_SERVICE_HOST=127.0.0.1
WEB_PORT=$WEB_UI_SERVICE_PORT
set +a
printenv
cd /app && ./web-ui serve 2>&1 | s6-log p"[web-ui]" 1